import type { Review } from '~/types/content'

export default defineEventHandler((): Review[] => {
  return [
    {
      id: 1,
      type: 'video',
      author: '@alika_smekhova',
      feedback_preview: 'Если правильно вкладываться в свой организм (правильным питанием, полноценным сном, хорошим настроением), то он ответит тебе взаимностью!',
      photo_urls: ['http://localhost:3000/images/mock/review/preview.png'],
      video_url: 'https://www.w3schools.com/html/mov_bbb.mp4',
      duration: '00:30',
      productIds: [1, 3],
    },
    {
      id: 2,
      type: 'text',
      author: 'Анна Смирнова',
      feedback_preview: 'Очень понравилось качество!',
      photo_urls: ['http://localhost:3000/images/mock/review/review-avatar.webp'],
      file_url: 'https://example.com/review-detail/2',
      productIds: [1, 3],
    },
    {
      id: 3,
      type: 'celebrity',
      author: '@alika_smekhova',
      preview: 'http://localhost:3000/images/mock/review/stories.png',
      photo_urls: ['http://localhost:3000/images/mock/review/review-avatar.webp'],
      mediaStory: ['http://localhost:3000/images/mock/review/review-avatar.webp'],
      productIds: [1, 15],
    },
    {
      id: 4,
      type: 'audio',
      author: 'Анна Смирнова',
      feedback_preview: 'Эссенция помогла восстановить кожу.',
      photo_urls: ['http://localhost:3000/images/mock/review/preview.png'],
      file_url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
      productIds: [1, 15],
    },
    {
      id: 5,
      type: 'celebrity',
      author: '@alika_smekhova',
      preview: 'http://localhost:3000/images/mock/review/stories.png',
      photo_urls: ['http://localhost:3000/images/mock/review/review-avatar.webp'],
      mediaStory: ['http://localhost:3000/images/mock/review/review-avatar.webp'],
      productIds: [1, 15],
    },
    {
      id: 6,
      type: 'celebrity',
      author: '@alika_smekhova',
      preview: 'http://localhost:3000/images/mock/review/stories.png',
      photo_urls: ['http://localhost:3000/images/mock/review/review-avatar.webp'],
      mediaStory: ['http://localhost:3000/images/mock/review/review-avatar.webp'],
      productIds: [1, 15],

    },
    {
      id: 7,
      type: 'celebrity',
      author: '@alika_smekhova',
      preview: 'http://localhost:3000/images/mock/review/stories.png',
      photo_urls: ['http://localhost:3000/images/mock/review/review-avatar.webp'],
      mediaStory: ['http://localhost:3000/images/mock/review/review-avatar.webp'],

    },
    {
      id: 8,
      type: 'video',
      author: '@alika_smekhova',
      feedback_preview: 'Если правильно вкладываться в свой организм...',
      photo_urls: ['http://localhost:3000/images/mock/review/preview.png'],
      video_url: 'https://example.com/review-1.mp4',
      duration: '00:30',
      productIds: [1, 3],
    },
    {
      id: 9,
      type: 'video',
      author: '@alika_smekhova',
      feedback_preview: 'Если правильно вкладываться в свой организм...',
      photo_urls: ['http://localhost:3000/images/mock/review/preview.png'],
      video_url: 'https://example.com/review-1.mp4',
      duration: '00:30',
      productIds: [1, 3],
    },
    {
      id: 10,
      type: 'audio',
      author: 'Анна Смирнова',
      feedback_preview: 'Эссенция помогла восстановить кожу.',
      photo_urls: ['http://localhost:3000/images/mock/review/preview.png'],
      file_url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
      productIds: [1, 3],
    },
    {
      id: 11,
      type: 'text',
      author: 'Анна Смирнова',
      feedback_preview: 'Очень понравилось качество! Очень понравилось качество! Очень понравилось качество! Очень понравилось качество!',
      file_url: 'https://example.com/review-detail/2',
      productIds: [1, 3],
    },
  ]
})
