import type { Review } from '~/types/content'

export default defineEventHandler((): Review[] => {
  return [
    {
      id: 1,
      type: 'video',
      author: 'Елена Туруева',
      feedback_preview: 'Применяли для лечения детишек, я и сама это принимала, и не осталось ни одного отрицательного отзыва...',
      photo_urls: ['https://s3.firstvds.ru/feedbacks/video/daigo-2.png'],
      file_url: 'https://s3.firstvds.ru/feedbacks/video/daigo-2.mp4',
      duration: '00:44',
      productIds: ['cafac368-1074-417d-bb3e-4470b4e28190', '71700acb-3584-490b-a5f7-62e8cb57b3c9'],
    },
    {
      id: 2,
      type: 'text',
      author: 'Анна Смирнова',
      feedback_preview: 'Очень понравилось качество!',
      photo_urls: ['http://localhost:3000/images/mock/review/review-avatar.webp'],
      file_url: 'https://example.com/review-detail/2',
      productIds: ['cafac368-1074-417d-bb3e-4470b4e28190', '71700acb-3584-490b-a5f7-62e8cb57b3c9'],
    },
    {
      id: 3,
      type: 'celebrity',
      author: 'Елена Летучая',
      preview: 'https://feedbacks.s3.firstvds.ru/stars/elena.jpg',
      photo_urls: ['https://feedbacks.s3.firstvds.ru/stars/elena.jpg'],
      mediaStory: ['https://feedbacks.s3.firstvds.ru/stars/letuchaya.mp4'],
      productIds: ['cafac368-1074-417d-bb3e-4470b4e28190', '71700acb-3584-490b-a5f7-62e8cb57b3c9'],
    },
    {
      id: 4,
      type: 'audio',
      author: 'Аноним',
      feedback_preview: 'Буквально через 2-3 дня у меня было ощущение бодрости и нового взгляда на вещи...',
      photo_urls: ['https://products.s3.firstvds.ru/tamotsu/effect.png'],
      file_url: 'https://s3.firstvds.ru/feedbacks/audio/tamotsu.mp3',
      productIds: ['34572cff-889e-4baa-b269-9c4a976dd381'],
    },
    {
      id: 5,
      type: 'celebrity',
      author: 'Дмитрий Маликов',
      preview: 'https://s3.firstvds.ru/feedbacks/stars/malikov.jpg',
      photo_urls: ['https://s3.firstvds.ru/feedbacks/stars/malikov.jpg'],
      mediaStory: ['https://s3.firstvds.ru/feedbacks/stars/malikov.mp4'],
      productIds: [],
    },
    {
      id: 6,
      type: 'celebrity',
      author: 'Алёна Долецкая',
      preview: 'https://feedbacks.s3.firstvds.ru/stars/doleckaya.png',
      photo_urls: ['https://feedbacks.s3.firstvds.ru/stars/doleckaya.png'],
      mediaStory: ['https://feedbacks.s3.firstvds.ru/stars/doleckaya.mp4'],
      productIds: [1, 15],

    },
    {
      id: 8,
      type: 'video',
      author: 'Аноним',
      feedback_preview: 'Если правильно вкладываться в свой организм...',
      photo_urls: ['https://s3.firstvds.ru/feedbacks/video/lux.png'],
      file_url: 'https://s3.firstvds.ru/feedbacks/video/lux.mp4',
      duration: '00:30',
      productIds: ['6dd5b27c-65fa-4de2-ada7-472f233cf60a'],
    },
    {
      id: 9,
      type: 'video',
      author: 'Аноним',
      feedback_preview: 'Если правильно вкладываться в свой организм...',
      photo_urls: ['https://s3.firstvds.ru/feedbacks/video/daigo-10.png'],
      file_url: 'https://s3.firstvds.ru/feedbacks/video/daigo10.MOV',
      duration: '00:30',
      productIds: ['cafac368-1074-417d-bb3e-4470b4e28190'],
    },
    {
      id: 10,
      type: 'audio',
      author: 'Аноним',
      feedback_preview: 'Мы 2 месяца пропили препарат Daigo, должны были 3, но слава богу на третий уже все прошло...',
      photo_urls: ['https://products.s3.firstvds.ru/emperor/prod-1.png'],
      file_url: 'https://s3.firstvds.ru/feedbacks/audio/lux-1.mp3',
      productIds: ['6dd5b27c-65fa-4de2-ada7-472f233cf60a'],
    },
    {
      id: 11,
      type: 'text',
      author: 'Аноним',
      feedback_preview: 'Применяла Дайго при лечении розацея по назначению врача. После недели приема было видно улучшение (краснота стала менее явной, папулы стали уменьшаться). Схема прописанная врачом: Дайго утром, биовестин лакто (днем или вечером), убрать белую муку и все с ней связанное и молоко. После месяца приема, биовестин был отменен, Дайго врач оставила еще на месяц. Общее самочувствие очень улучшилось, прошли бурление, боли в животе. Розацея ушла через 2 месяца. Была применена фото терапия, которая до этого стойкого результата не давала. Прошел год с момента применения Дайго, розацеа не вернулась. Повторные сеансы фототерапии за год не понадобились. Препарат рекомендую! Спасибо!',
      productIds: ['cafac368-1074-417d-bb3e-4470b4e28190', '71700acb-3584-490b-a5f7-62e8cb57b3c9'],
    },
    {
      id: 12,
      type: 'text',
      author: 'Анна Смирнова',
      feedback_preview: 'Очень давно педиатр порекомендовал мне продукцию Дайго, но только сейчас я решилась ее попробовать, и я крайне довольна результатом. После почти месяца применения я заметила явные улучшения: у меня появилась легкость, и у меня больше нет вздутия живота. Также, согласно результатам анализов, улучшилось состояние дисбактериоза, который был у меня ранее диагностирован. Я также заметила сокращение симптомов лактозной недостаточности. Уже несколько лет после родов я не могла есть яйца, но теперь уже неделю я ем омлет по утрам без каких-либо проблем.Я хотела бы выразить огромную благодарность за прекрасный продукт и отличный сервис. Консультации были очень подробными и грамотными, а доставка - молниеносной.',
      file_url: 'https://example.com/review-detail/2',
      productIds: ['cafac368-1074-417d-bb3e-4470b4e28190', '71700acb-3584-490b-a5f7-62e8cb57b3c9'],
    },
    {
      id: 13,
      type: 'text',
      author: 'Анна Смирнова',
      feedback_preview: 'Добрый день. Впервые метабиотик Дайго появился в нашей семье осенью 2021 года. Старшему сыну тогда было почти три года, и мы заметили, что у него стал хуже аппетитит, он стал раздражительный, плаксивый и даже бледнее. Мы  сдали анализы и пришли в ужас: почти все показатели отличались от нормы, но больше всего пугал гемоглобин - он был 80!Гемоглобин падал, а показатель СОЭ стремительно рос. Мы конечно сразу обратились к врачу, нам назначили консультацию гематолога, которые назначили кучу анализов, но толком причину не нашли. И нам повезло, что мы нашли толкового врача: по анализам сына (при дообследовании у него обнаружили очень высокий ферритин), был поставлен диагноз: нарушение проницаемости кишечника. Т.е. железо не усваивалось, а копилось в организме, т.е. образовалось некое депо. Нужен был очень хороший пробиотик и железо. Сыну был назначен Дайго и хорошее легкоусваиваемое трехвалетное немецкое железо. Через месяц сына было не узнать: аппетит вернулся, румяный, весёлый. Со страхом я ждала результатов анализа крови: гемоглобин вырос до 112 (с 80) , ферритин пришёл в норму, СОЭ упала в два раза! Мы пропили курс три месяца: по одному пакетику Дайго натощак. Через три месяца анализ крови был в норме, гемоглобин 125, СОЭ опустилась с 70!!! за 4 месяца до возврастной нормы.С тех пор каждые полгода мы покупаем этот чудесный продукт и уже двое детей пропивают месячный курс для профилактики. Конечно, из-за сада болеют они нередко, но без осложнений! Думаю в этом тоже заслуга Дайго! Сейчас на сайте отличная акция 2+1 , мы конечно с радостью ей воспользовались, и начали готовиться к осеннему сезону) Очень порадовала не только акция, но и очень быстрая доставка: в 10 утра я оформила заказ, а в два часа дня заказ был уже у нас! Хотя мы живём в Подмосковье) Спасибо большое за ваш труд и за такой чудесный продукт',
      file_url: 'https://example.com/review-detail/2',
      productIds: ['cafac368-1074-417d-bb3e-4470b4e28190', '71700acb-3584-490b-a5f7-62e8cb57b3c9'],
    },
    {
      id: 14,
      type: 'audio',
      author: 'Аноним',
      feedback_preview: 'Нам рекомендовали врачи Daigo, но были сомнения, и когда очень хороший врач назначил все сомнения отпали. Тяжелого ребенка подняла на ноги в плане жкт и...',
      photo_urls: ['https://products.s3.firstvds.ru/daigo-5/instructions.png'],
      file_url: 'https://s3.firstvds.ru/feedbacks/audio/daigo5-1.mp3',
      productIds: ['71700acb-3584-490b-a5f7-62e8cb57b3c9'],
    },
  ]
})
